INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (1, 'APT 1111', '1111 EAST PR LANE', 'AUSTIN', 'TRAVIS', '11111', 'TX', 'US');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (2, 'APT 2222', '2222 EAST PR LANE', 'MACCENY', 'BAKER', '22222', 'FL', 'US');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (3, 'APT 3333', '3333 EAST PR LANE', 'HILLSVILLE', 'CARROLL', '33333', 'VA', 'US');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (4, 'APT 4444', '4444 EAST PR LANE', 'GREENVILLE', 'DARKE', '44444', 'OH', 'US');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (5, 'APT 5555', '5555 WEST PR LANE', 'ALLEGANY', 'BELONT', '55555', 'NY', 'US');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (6, 'APT 6666', '6666 WEST PR LANE', 'LITTLE ROCK', 'PULASKI', '66666', 'AR', 'US');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (7, 'APT 7777', '7777 WEST PR LANE', 'MOBILE', 'HOUSTON', '77777', 'AL', 'US');

INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (8, 'APT 4011', '4011 1ST AVENUE', 'MONTREAL', 'COUNTY TEST1', 'G9A 5S0', 'QC', 'CA');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (9, 'APT 4012', '4012 1ST AVENUE', 'HALIFAX', 'COUNTY TEST2', 'G9A 5S1', 'NS', 'CA');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (10, 'APT 4013', '4013 1ST AVENUE', 'MONCTON', 'COUNTY TEST3', 'G9A 5S2', 'NB', 'CA');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (11, 'APT 4014', '4014 ADELAIDE STREET', 'WINNIPEG', 'COUNTY TEST4', 'MSH 1P0', 'MB', 'CA');
INSERT INTO ADDRESS (ID, UNIT, STREET, CITY, COUNTY, ZIPCODE, STATE, COUNTRY) VALUES (12, 'APT 4015', '4015 ADELAIDE STREET', 'VANCOUVER', 'COUNTY TEST5', 'MSH 1P2', 'BC', 'CA');